### ISSUE TITLE
add Fdroid repo

### ISSUE THREAD

**Issue by pyluyten** [fbarthelery/geekttrss#6]
i'm fine with Play Store, but you would certainly gain users there

**Comment by fbarthelery** [comment]
I, personally, don't like the F-Droid approach regarding packaging. The fact that they recompile and re-sign the application bothers me. On some previous projects, I had some issues reported due to the distribution of an incorrect APK on their repository.

However, feel free to submit a request for packaging on the [F-Droid tracker](https://f-droid.org/en/contribute/).

**Comment by Poussinou** [comment]
I opened a Request For Packaging here: https://gitlab.com/fdroid/rfp/issues/952

**Comment by fbarthelery** [comment]
I'll keep this issue open until the RFP on the F-Droid tracker is closed

**Comment by infeeeee** [comment]
For those who want to install this with f-droid, it's available from IzzyOnDroid's repo: https://apt.izzysoft.de/fdroid/index/apk/com.geekorum.ttrss.free

To add the repo: https://apt.izzysoft.de/fdroid/index.php

**Comment by IzzySoft** [comment]
@fbarthelery it seems there are some issues with the F-Droid inclusion ([reference](https://gitlab.com/fdroid/rfp/-/issues/952#note_305419168)). Quote:

> The main remaining problem is these prebuilt libraries: https://github.com/fbarthelery/geekttrss/tree/master/libs

Firebase would be a general show-stopper (but if I understood correctly, the special flavor should exclude it). Are the sources for geekdroid available publically, so we could make that a `srclib` at F-Droid?

**Comment by fbarthelery** [comment]
> Firebase would be a general show-stopper (but if I understood correctly, the special flavor should exclude it). Are the sources for geekdroid available publically, so we could make that a srclib at F-Droid?
Yes the free flavor exclude Firebase and other non opensource libraries.

I still have some work to do before publishing the geekdroid libraries and make it usable. (it wasn't really on my todo list). Would it be enough if I just dump the sources in a Github repository?

**Comment by IzzySoft** [comment]
as I cannot tell exactly: @rudloff @licaon-kter ?

**Comment by licaon-kter** [comment]
@fbarthelery yes, even better if pull them as a gitmodule or how will you use them?

**Comment by fbarthelery** [comment]
I think I'm going to keep using a prebuilt jar or use [JitPack](https://jitpack.io/) for now

**Comment by IzzySoft** [comment]
@fbarthelery with a prebuilt Jar, inclusion in F-Droid won't be possible. JitPack [would be fine](https://gitlab.com/fdroid/fdroidserver/blob/master/fdroidserver/scanner.py#L99).

**Comment by licaon-kter** [comment]
@fbarthelery Adding jitpack.io ut still fails
```
* Where:
Build file '/home/strech/fdroiddata/build/com.geekorum.ttrss.free/build.gradle.kts' line: 22

* What went wrong:
Script compilation errors:

  Line 22: import com.geekorum.build.SourceLicenseCheckerPlugin
                      ^ Unresolved reference: geekorum

  Line 23: import com.geekorum.build.configureJavaVersion
                      ^ Unresolved reference: geekorum

  Line 24: import com.geekorum.build.createComponentsPlatforms
                      ^ Unresolved reference: geekorum

  Line 25: import com.geekorum.build.setupGoogleContent
                      ^ Unresolved reference: geekorum

  Line 44:         google().setupGoogleContent()
                            ^ Unresolved reference: setupGoogleContent

  Line 55:         createComponentsPlatforms()
                   ^ Unresolved reference: createComponentsPlatforms

  Line 58:     apply<SourceLicenseCheckerPlugin>()
                     ^ Unresolved reference: SourceLicenseCheckerPlugin

  Line 72:             configureJavaVersion()
                       ^ Unresolved reference: configureJavaVersion

8 errors
```
ignore the line number since I'm cleaning non-FOSS libs

**Comment by fbarthelery** [comment]
Sources for the `com.geekorum.build` package are in [buildSrc](https://github.com/fbarthelery/geekttrss/tree/master/buildSrc). They should be compiled automatically by gradle if the `buildSrc` folder is present

**Comment by licaon-kter** [comment]
Oh, didn't know...will try...

**Comment by fbarthelery** [comment]
More info here if you are interested 
https://docs.gradle.org/current/userguide/organizing_gradle_projects.html#sec:build_sources

**Comment by fbarthelery** [comment]
@licaon-kter 
I published the sources of the geekdroid library [here](https://github.com/fbarthelery/geekdroid).
The master branch of Geekttrss use jitpack to get it.

Alternatively, you can set a the `GEEKDROID_PROJECT_DIR` in [gradle.properties](https://github.com/fbarthelery/geekttrss/blob/5a6ed316b569805e1f7f3eba7e621b247b926356/gradle.properties#L28) or as command line flags (-PGEEKDRDOID_PROJECT_DIR) and the build will use the sources instead of the jitpack build.

Let me know if there is anything else I can do to help.

**Comment by IzzySoft** [comment]
@fbarthelery by the way, you forgot to adjust versionCode and versionName for [1.5.0](https://github.com/fbarthelery/geekttrss/tree/1.5.0). APK still identifies as

    package: name='com.geekorum.ttrss.free' versionCode='1041555' versionName='1.4.1' compileSdkVersion='29' compileSdkVersionCodename='10'

Can you please fix that (and create a new tag with an APK attached)? Thanks!

**Comment by fbarthelery** [comment]
Good catch @IzzySoft ! Looks like I uploaded an older apk instead. I edited the release to attach the correct apk.
[Grab it here](https://github.com/fbarthelery/geekttrss/releases/tag/1.5.0)

Thank you

**Comment by IzzySoft** [comment]
Thanks for the fast fix @fbarthelery! Updated it in my repo (will show up in about 7 hours with the next sync).

**Comment by erazemkokot** [comment]
@fbarthelery I'm guessing this can be closed, since the app was successfully published to F-Droid.

**Comment by licaon-kter** [comment]
Things got piled up, I didn't get around to retest....but no, this is not in F-Droid atm.

**Comment by erazemkokot** [comment]
> Things got piled up, I didn't get around to retest....but no, this is not in F-Droid atm.

Oh, my bad, after checking I downloaded it from Izzy's repo.

**Comment by erazemkokot** [comment]
The F-Droid app just makes it so convenient to not even have to think where the apps are coming from once you import the repos 😂, but yeah, you should totally take it as a compliment, your repo and the way you automated it are pretty cool.

**Comment by licaon-kter** [comment]
Decentralization is an F-Droid goal, so @IzzySoft is doing a great service ;)

**Comment by IzzySoft** [comment]
So what @erazemkokot just wrote is a compliment to both :partying_face: :champagne: Thanks!

**Comment by licaon-kter** [comment]
```
ERROR: Found unknown maven repo 'https://raw.githubusercontent.com/fbarthelery/play-services-plugins/master/repo/' at settings.gradle.kts
ERROR: Found usual suspect 'google.*play.*services' at app/build.gradle.kts
ERROR: Found usual suspect 'com(\.google)?\.firebase[.:](?!firebase-jobdispatcher|geofire-java)' at app/build.gradle.kts
ERROR: Found usual suspect 'androidx.navigation:navigation-dynamic-features' at app/build.gradle.kts
```

**Comment by fbarthelery** [comment]
> `ERROR: Found unknown maven repo 'https://raw.githubusercontent.com/fbarthelery/play-services-plugins/master/repo/' at settings.gradle.kts`

I have to remove it it should not be needed anymore.


> ERROR: Found usual suspect 'google.*play.*services' at app/build.gradle.kts
> ERROR: Found usual suspect 'com(\.google)?\.firebase[.:](?!firebase-jobdispatcher|geofire-java)' at app/build.gradle.kts

Play services plugin is not applied on free variant. Same for firebase dependencies

> ERROR: Found usual suspect 'androidx.navigation:navigation-dynamic-features' at app/build.gradle.kts

navigation-dynamic-features-* are on Apache 2 license according to [this](https://maven.google.com/web/index.html?q=navigation#androidx.navigation:navigation-dynamic-features-fragment:2.5.3)

@licaon-kter let me know if I'm wrong

**Comment by fbarthelery** [comment]
> Is this fixed? https://issuetracker.google.com/issues/237574816?pli=1 if not, then **its** deps are not FOSS ;)

Seems to be fixed.  
I guess you are thinking about the `com.google.android.play:core:1.10.3` library. This dependency is exclude on the free variant

**Comment by licaon-kter** [comment]
```
  - versionName: 1.6.0
    versionCode: 1060000
    commit: e6423dfba9f7b5b85c216256c65dfe10278a808a
    subdir: app
    gradle:
      - free
    prebuild:
      - sed -i -e '/play-/d' -e '/firebase-bom/,+7d' -e '/dynamic-features-fragment/d'
        build.gradle.kts
      - sed -i -e '/maven {/,+4d' ../settings.gradle.kts
      - sed -i -e 's/versionCode = .*/versionCode = "$$VERCODE$$"/' -e 's/changeset
        = .*/changeset = "unknown"/' ../buildSrc/src/main/kotlin/RepositoryChangeset.kt
```

So we remove some "usual suspects", we remove your "custom repo" so then it fails with:
```
> Task :app:processFreeReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processFreeReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     ERROR:/home/vagrant/build/com.geekorum.ttrss.free/app/src/main/res/navigation/add_feed_installer.xml:40: AAPT: error: attribute moduleName (aka com.geekorum.ttrss.free:moduleName) not found.
         
     ERROR:/home/vagrant/build/com.geekorum.ttrss.free/app/src/main/res/navigation/add_feed_installer.xml:51: AAPT: error: attribute moduleName (aka com.geekorum.ttrss.free:moduleName) not found.
         
     ERROR:/home/vagrant/build/com.geekorum.ttrss.free/app/src/main/res/navigation/articles_list.xml:112: AAPT: error: attribute moduleName (aka com.geekorum.ttrss.free:moduleName) not found.
         
     ERROR:/home/vagrant/build/com.geekorum.ttrss.free/app/src/main/res/xml/pref_general.xml:67: AAPT: error: resource string/oss_license_title (aka com.geekorum.ttrss.free:string/oss_license_title) not found.
```

...as expected right? Per https://github.com/fbarthelery/geekttrss/blob/master/settings.gradle.kts#L45-L48

We also hardcode versionname and versioncode as `hg` (mercurial) will fail (error code 255) somewhere around here https://github.com/fbarthelery/geekttrss/blob/5b1dc61ca34d737611d58e8cd5c66729492acbd1/buildSrc/src/main/kotlin/RepositoryChangeset.kt

**Comment by fbarthelery** [comment]
I just release version [1.6.1](https://github.com/fbarthelery/geekttrss/releases/tag/1.6.1)

The following changes should not be necessary anymore:
  - remove the "custom repo"
  - hardcoded versionname and versioncode: mercurial should not have been called if the repo is not a mercurial repo. 

Regarding your "usual suspects" list, my only issue is with `navigation-dynamic-features-fragment`. As I said previously, it's on Apache 2 license. It has a dependency on `com.google.android.play:feature-delivery` which is not opensource, but is exclude on the `free` variant, so it should not be an issue.

` Android resource linking failed
    ERROR:/home/vagrant/build/com.geekorum.ttrss.free/app/src/main/res/navigation/add_feed_installer.xml:40: AAPT: error: attribute moduleName (aka com.geekorum.ttrss.free:moduleName) not found.  
     ERROR:/home/vagrant/build/com.geekorum.ttrss.free/app/src/main/res/navigation/add_feed_installer.xml:51: AAPT: error: attribute moduleName (aka com.geekorum.ttrss.free:moduleName) not found.
     ERROR:/home/vagrant/build/com.geekorum.ttrss.free/app/src/main/res/navigation/articles_list.xml:112: AAPT: error: attribute moduleName (aka com.geekorum.ttrss.free:moduleName) not found.
`
These errors are because you removed `navigation-dynamic-features-fragment`. The library declares the `moduleName` attribute. 

 `  ERROR:/home/vagrant/build/com.geekorum.ttrss.free/app/src/main/res/xml/pref_general.xml:67: AAPT: error: resource string/oss_license_title (aka com.geekorum.ttrss.free:string/oss_license_title) not found.`
This one comes from removing "com.google.android.gms:play-services-oss-licenses:17.0.0". It should not happen anymore on latest version as I remove the library and replace it with my own implementation.

**Comment by licaon-kter** [comment]
> it's on Apache 2 license. It has a dependency on com.google.android.play:feature-delivery which is not opensource, but is exclude on the free variant, so it should not be an issue. 

Yes and no, basically the artifacts are built from non-FOSS code? If so... they're not FOSS no matter if you "remove the deps at runtime".

**Comment by fbarthelery** [comment]
I get your point. I'm not sure I agree with it but if it's F-Droid policy I understand.

So you won't be able to build version 1.6.1 if you remove  navigation-dynamic-features-fragment. I think I can work to totally remove it from the free variant, but it will be for next version. In the meantime, can you try to build it anyway and let me know if you encounter other issues?

**Comment by fbarthelery** [comment]
@licaon-kter 

I just published [1.6.2](https://github.com/fbarthelery/geekttrss/releases/tag/1.6.2)
This version doesn't use navigation-dynamic-features-fragment for the free variant, so I think that all your concerns are fixed now.

Let me know if something else comes up

**Comment by licaon-kter** [comment]
The APK builds, this draft recipe:
```
  - versionName: 1.6.2
    versionCode: 1062000
    commit: fb7368ae0ff437485fc736ce8833e40b4b1fa035
    subdir: app
    sudo:
      - apt-get update
      - apt-get install mercurial
    gradle:
      - free
```

But, any chance to have versionName/versionCode as static or provided somewhere so we can enable autoupdate?

Reproducibility appears close: [rb.zip](https://github.com/fbarthelery/geekttrss/files/11064805/rb.zip)

The baseline thing could be fixed like this: https://f-droid.org/docs/Reproducible_Builds/#potential-sources-of-unreproducible-builds

But the rest of the differences... any thoughts? Some sorting issue?

**Comment by fbarthelery** [comment]
> But, any chance to have versionName/versionCode as static or provided somewhere so we can enable autoupdate?

Would it be ok, I i fixed versionCode and VersionName on release ? 

For the rest of differences I have a few guess.
Are you diffing with [my release build](https://github.com/fbarthelery/geekttrss/releases/tag/1.6.2) ? If yes, on my CI the [google play services plugin is enabled](https://github.com/fbarthelery/geekttrss/blob/master/app/build.gradle.kts#L282) even during the build of the free variant. That will explain the differences in `res/values/strings.xml` and `res/values/public.xml`

As the application uses features modules, you also need to use the generated APK from `build/outputs/apk_from_bundle/` directory which merge the app module and the manage_feeds module. I think this should fix the differences in AndroidManifest.xml

`res/raw/third_party_license_metadata` is generated by the [OSS license plugin](https://github.com/google/play-services-plugins/tree/master/oss-licenses-plugin) I think the resulting ordering depends on the order of downloading dependencies.

**Comment by licaon-kter** [comment]
> res/raw/third_party_license_metadata is generated by the OSS license plugin I think the resulting ordering depends on the order of downloading dependencies.

Umm, that is not FOSS (it depends on play-*), the scanner should have picked it up... will need to look inside the VM

**Comment by IzzySoft** [comment]
> Umm, that is not FOSS (it depends on play-*), the scanner should have picked it up

Didn't it? You've [wrote so](#issuecomment-1330609601) in November. And @fbarthelery answered it would be removed. So how can it be (or cause) a dependency then? :thinking:

**Comment by fbarthelery** [comment]
Let me clarify.

The OSS license plugin is a gradle plugin used during build to collect license dependency info. It is totally free and opensource. It generates 2 files `res/raw/third_party_license` and `res/raw/third_party_license_metadata`. These contains the text of the opensource licenses and a where to find the beginning of the license text for each dependency (metadata). 
It is usually used with the "com.google.android.gms:play-services-oss-licenses" library which contains some code that read these 2 generated files at runtime and display their information in an activity.  This library in not opensource and I replaced it with my own implementation 37afa800bd30011703613b5aabb682193ca3a076.

**Comment by IzzySoft** [comment]
> It is usually used with the "com.google.android.gms:play-services-oss-licenses" library which contains some code that read these 2 generated files at runtime and display their information in an activity. This library in not opensource and I replaced it with my own implementation

That's the missing piece on that end, thanks! As a side-question on that: is your replacement library available for other projects, maybe even with instructions on how to replace the dependency? Then I'd include it with [my hints on license dialogs](https://gitlab.com/-/snippets/1896503#license-dialogs) (like I did with the flutter geolocation one further down on that page)..

**Comment by fbarthelery** [comment]
At the moment, reading the files is in [Geekdroid](https://github.com/fbarthelery/geekdroid/tree/master/geekdroid/src/main/java/com/geekorum/geekdroid/osslicenses) and the UI is specific to [Geekttrss](https://github.com/fbarthelery/geekttrss/tree/master/app/src/main/java/com/geekorum/ttrss/settings/licenses). I'll have to extract them in a separate library to make it more reusable. I put that on my TODO list.

**Comment by fbarthelery** [comment]
I just published [1.6.3](https://github.com/fbarthelery/geekttrss/releases/tag/1.6.3)

@IzzySoft  This version use my new [AboutOss](https://github.com/fbarthelery/AboutOss) library to display licenses information

Regarding the integration to the F-Droid repo, is there a tracker that I can follow?

**Comment by licaon-kter** [comment]
Umm https://gitlab.com/fdroid/rfp/-/issues/952 but I forgot to put my trial recipes there, yet you can see them above

Will retry 1.6.3 asap

**Comment by IzzySoft** [comment]
> This version use my new [AboutOss](https://github.com/fbarthelery/AboutOss) library to display licenses information

Thanks, added to the list!

**Comment by licaon-kter** [comment]
> As the application uses features modules, you also need to use the generated APK from build/outputs/apk_from_bundle/ directory which merge the app module and the manage_feeds module

There's none to pickup :shrug: 
```
$ find . -iname "*.apk"
./unsigned/com.geekorum.ttrss.free_1063000.apk
./build/com.geekorum.ttrss.free/app/build/outputs/apk/free/release/app-free-release-unsigned.apk
```

**Comment by licaon-kter** [comment]
`gradle assembleFreeRelease`

We need to test your others then...

**Comment by licaon-kter** [comment]
Maybe closer?
recipe **metadata/com.geekorum.ttrss.free.yml**
```
License: Unknown
SourceCode: https://github.com/fbarthelery/geekttrss
IssueTracker: https://github.com/fbarthelery/geekttrss/issues

RepoType: git
Repo: https://github.com/fbarthelery/geekttrss.git
Binaries: https://github.com/fbarthelery/geekttrss/releases/download/%v/geekttrss-%v-free-release.apk

Builds:
  - versionName: 1.6.3
    versionCode: 1063000
    commit: 303c3b5f1699c9cd4c671ca15d708f09df7ccc51
    subdir: app
    output: build/outputs/apk_from_bundle/freeRelease/app-free-release-universal-unsigned.apk
    prebuild: gradle clean
    build: gradle packageFreeReleaseUniversalApk

AllowedAPKSigningKeys: 3ee607c1a61b33402027589a6270bb5f6617950d1530826d1c3d1f5031394320

AutoUpdateMode: None
UpdateCheckMode: Tags
```

Diff log: 
[geek1.zip](https://github.com/fbarthelery/geekttrss/files/11285009/geek1.zip)

**Comment by fbarthelery** [comment]
I'm not sure for `baseline.prof` but it looks like the remaining differences are caused by me having the google services and crashlytics plugin enabled when building the free variant, which I think should be fixed on my side.

**Comment by fbarthelery** [comment]
I just released 1.6.4.

This release reduce the differences with your own build as the google-services plugin is not applied anymore when building the free variant

**Comment by licaon-kter** [comment]
recipe:
```
License: Unknown
SourceCode: https://github.com/fbarthelery/geekttrss
IssueTracker: https://github.com/fbarthelery/geekttrss/issues

RepoType: git
Repo: https://github.com/fbarthelery/geekttrss.git
Binaries: https://github.com/fbarthelery/geekttrss/releases/download/%v/geekttrss-%v-free-release.apk

Builds:
  - versionName: 1.6.4
    versionCode: 1064000
    commit: 16e7eb3562ee9206e53f10e6acd463e93f512de6
    subdir: app
    sudo:
      - apt-get update
      - apt-get install -y openjdk-17-jdk-headless
      - update-java-alternatives -a
    output: build/outputs/apk_from_bundle/freeRelease/app-free-release-universal-unsigned.apk
    prebuild: gradle clean
    build: gradle packageFreeReleaseUniversalApk

AllowedAPKSigningKeys: 3ee607c1a61b33402027589a6270bb5f6617950d1530826d1c3d1f5031394320

AutoUpdateMode: None
UpdateCheckMode: Tags
```
...diff log: 
[geek164.log](https://github.com/fbarthelery/geekttrss/files/11477289/geek164.log)

**Comment by fbarthelery** [comment]
I still don't know for `baseline.prof`, is it going to be an issue ? 
Ordering differences only for `third_party_license_metadata`
`SettingsFragment` it's weird that we didn't notice it before. Anyway the github repository is a mirror, the main repository is a mercurial repository self hosted here https://hg.elyzion.net/geekttrss/geekttrss/

**Comment by licaon-kter** [comment]
If classes is different, so is baseline

But why does it hardcode that string?

**Comment by fbarthelery** [comment]
It's a BuildConfig field (see [here](https://github.com/fbarthelery/geekttrss/blob/16e7eb3562ee9206e53f10e6acd463e93f512de6/buildSrc/src/main/kotlin/RepositoryChangeset.kt#L157)) used [here](https://github.com/fbarthelery/geekttrss/blob/16e7eb3562ee9206e53f10e6acd463e93f512de6/app/src/main/java/com/geekorum/ttrss/settings/SettingsActivity.kt#L136). I guess it gets inlined in the class

**Comment by licaon-kter** [comment]
So we can switch to the "real" source and that would fix them all? Will try

**Comment by fbarthelery** [comment]
Yes I think it will, if you clone the mercurial repository using hg

**Comment by licaon-kter** [comment]
Ok, so updated:
```
License: Unknown
SourceCode: https://github.com/fbarthelery/geekttrss
IssueTracker: https://github.com/fbarthelery/geekttrss/issues

RepoType: hg
Repo: https://hg.elyzion.net/geekttrss/geekttrss
Binaries: https://github.com/fbarthelery/geekttrss/releases/download/%v/geekttrss-%v-free-release.apk

Builds:
  - versionName: 1.6.4
    versionCode: 1065043
    commit: 21cdf3d6433d
    subdir: app
    sudo:
      - apt-get update
      - apt-get install -y openjdk-17-jdk-headless
      - update-java-alternatives -a
    output: build/outputs/apk_from_bundle/freeRelease/app-free-release-universal-unsigned.apk
    srclibs:
      - reproducible-apk-tools@v0.2.3
    prebuild: gradle clean
    build: gradle packageFreeReleaseUniversalApk
    postbuild: $$reproducible-apk-tools$$/inplace-fix.py --zipalign fix-newlines $$OUT$$
        'res/raw/third_party_license_metadata'

AllowedAPKSigningKeys: 3ee607c1a61b33402027589a6270bb5f6617950d1530826d1c3d1f5031394320

AutoUpdateMode: None
UpdateCheckMode: Tags
```

Builds fine, but `res/raw/third_party_license_metadata` needs to be sorted, as it's the only think that currently is different in the APK.

Also, the versionCode is not static? It depends on commits number? :( https://github.com/fbarthelery/geekttrss/blob/16e7eb3562ee9206e53f10e6acd463e93f512de6/buildSrc/src/main/kotlin/RepositoryChangeset.kt#L86-L120

...this makes autoupdates impossible. Any chance to export versionName/Code to a file just before Tagging?

**Comment by fbarthelery** [comment]
> Ok, so updated:
> 
> ```
> License: Unknown
> ```

License is GPL-3

> Builds fine, but `res/raw/third_party_license_metadata` needs to be sorted, as it's the only think that's currently different in the APK.

This will need a little more work as it's from the play services plugin. I'll try to contribute a fix otherwise I'll probably have to fork it.

> Also, the versionCode is not static? It depends on commits number? :(

Yeah, I was waiting to fix the previous issues before working on that. So my plan is to export versionName/versionCode to a file that I will commit in the repository and update this file after release, so that means after tagging. Will this work for you ? Do you have any requirements for the file format ?

**Comment by licaon-kter** [comment]
Draft recipe, hence missing License ;)

Yes, having a repo file updated before tagging with versionCod and versionName is fine.
```
versionCode xxxx
versionName yy.yy
```
....or whatever, works fine.

**Comment by fbarthelery** [comment]
Hi @licaon-kter,

Can you try to build the latest commit on master (commit: 5a032a5d981c) and compare it with the attached file ? I had to rename it to .zip because of github.

[geekttrss-test-reproducible-free-release.apk.zip](https://github.com/fbarthelery/geekttrss/files/11737980/geekttrss-test-reproducible-free-release.apk.zip)

**Comment by licaon-kter** [comment]
Well... 
```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/vagrant/build/com.geekorum.ttrss.free/app/build.gradle.kts' line: 27

* What went wrong:
Plugin [id: 'com.google.android.gms.oss-licenses-plugin', version: '0.10.6.1', artifact: 'com.google.android.gms:oss-licenses-plugin:0.10.6.1'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.google.android.gms:oss-licenses-plugin:0.10.6.1')
  Searched in the following repositories:
    Gradle Central Plugin Repository
    MavenRepo
    Google
```

...the list of trusted repos is here: https://gitlab.com/fdroid/fdroidserver/-/blob/2a60f6c195dfd24149617ceb1df1731fb3bf50c8/fdroidserver/scanner.py#L452-L47 and your github repo is not allowed.

**Comment by licaon-kter** [comment]
Will try to bypass it next then.

Publish on those maven repos :)

**Comment by IzzySoft** [comment]
> What options do I have to use a fork of Oss licenses plugin ?

MAybe one of the [alternative license plugins](https://gitlab.com/-/snippets/1896503#license-dialogs) could help out? Hm, I wonder why that fork is not pointed out, I vaguely remember there was one…

**Comment by licaon-kter** [comment]
@fbarthelery yup, this recipe
```
  - versionName: 1.6.4
    versionCode: 1065061
    commit: 5a032a5d981
    subdir: app
    sudo:
      - apt-get update
      - apt-get install -y openjdk-17-jdk-headless
      - update-java-alternatives -a
    output: build/outputs/apk_from_bundle/freeRelease/app-free-release-universal-unsigned.apk
    prebuild: gradle clean
    build: gradle packageFreeReleaseUniversalApk
```
...is repro with that APK you've attached
